[package]
name = "http_server"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper_wasi = { version = "0.15.2", features = ["full"]}
tokio_wasi = { version = "1", features = ["rt", "macros", "net", "time", "io-util"]}
